---
- name: Configure LDAP settings
  jfrog.platform.artifactory_ldap_settings:
    jfrog.platform.artifactory_ldap_settings:
    ldap_settings: "{{ ldap_settings }}"
    artifactory_base_url: "{{ artifactory_url }}"
    state: "{{ ldap_settings_state }}"
    auth_type: "{{ artifactory_auth }}"
    {% if artifactory_auth == 'Basic' %}
    auth_string: "{{ artifactory_admin_username }}:{{ artifactory_admin_password }}"
    {% else %}
    auth_string: "{{ artifactory_auth_token }}"
    {% endif %}
    ignore_ca_error: "{{ artifactory_ignore_ca_error }}"
  when:
    - configure_ldap_settings

- name: Configure repositories in artifactory
  jfrog.platform.artifactory_repository:
    repository_configs: "{{ artifactory_repositories }}"
    artifactory_base_url: "{{ artifactory_url }}"
    state: "{{ artifactory_repository_state }}"
    auth_type: "{{ artifactory_auth }}"
    {% if artifactory_auth == 'Basic' %}
    auth_string: "{{ artifactory_admin_username }}:{{ artifactory_admin_password }}"
    {% else %}
    auth_string: "{{ artifactory_auth_token }}"
    {% endif %}
    ignore_ca_error: "{{ artifactory_ignore_ca_error }}"
  when: 
    - configure_repositories