- name: perform installation
  include_tasks: "install.yml"
  when:
    - artifactory_enabled
    - not artifactory_upgrade_only
- name: perform upgrade
  include_tasks: "upgrade.yml"
  when:
    - artifactory_enabled
    - artifactory_upgrade_only
- name: perform configuration
  include_tasks: "configure.yml"
  when: 
    - artifactory_enabled
    - artifactory_configure